def show_menu():
    print('\nMenu:')
    print('1 - Show available coins')
    print('2 - Show wallet')
    print('3 - Buy coin')
    print('4 - Sell coin')
    print('5 - Check transactions')
    print('6 - Show cources')
    print('7 - My account')
    print('0 - Exit')
